name: build 🔧

on:
  workflow_call:

env:
  NODE_VERSION: 16.x

jobs:
  build:
    name: 🔧
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          .git/
          build/
          .firebaserc
          firebase.json
