name: test 🧪

on:
  workflow_call:

env:
  NODE_VERSION: 16.x

jobs:
  test:
    name: 🧪
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
